# Generated by Django 3.2.5 on 2021-07-14 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(editable=False, max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('f_name', models.CharField(max_length=255)),
                ('s_name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=1000)),
                ('charge', models.IntegerField()),
                ('admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255, unique=True)),
                ('price', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('added_date', models.DateField()),
                ('img', models.ImageField(upload_to='pics')),
                ('category', models.ForeignKey(default='دسته بندی نشده', on_delete=django.db.models.deletion.SET_DEFAULT, to='pashmak.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('processing', 'در حال انجام'), ('done', 'انجام شده'), ('cancelled', 'لغو شده')], default='processing', max_length=225)),
                ('date', models.DateField()),
                ('f_name', models.CharField(max_length=255)),
                ('s_name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=1000)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pashmak.product')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pashmak.user')),
            ],
        ),
    ]
